config/routes.rb
Rails.application.routes.draw do
  #application routes
  get '/', to: 'static#welcome'
  get '/about', to: 'static#about'

  #players routes
  get '/players', to: 'players#index'
  get '/signup', to: 'players#new', as: 'signup'
  get '/players/new', to: 'players#new'
  get '/players/:id', to: 'players#show', as: 'player'
  get '/players/:id/edit', to: 'players#edit', as: 'edit_player'

  post '/players/', to: 'players#create'
  patch '/players/:id', to: 'players#update'
  delete '/players/:id', to: 'players#destroy'

  #sessions routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  #game routes
  post '/games', to: 'games#create'
  get '/games/:id/complete', to: 'games#complete'
  get '/games/:id/:status', to: 'games#guess'
  post '/games/:id/:status/:quote_id', to: 'games#assess'
  
  #quotes routes
  post '/quotes', to: 'quotes#create'
  get '/quotes/new', to: 'quotes#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :player_games
    has_many :players, through: :player_games
    has_many :rounds
    has_many :quotes, through: :rounds

    def setup_round
        Round.create(game_id: self.id, quote_id: Quote.all.sample.id)
    end

    def setup_game(player_id)
       5.times do setup_round end
       PlayerGames.create(game_id: self.id, player_id: player_id, score: 0, status: 0)
       #removed player_id: :sessions[user_id]
    end

    def assign_player
    end

end

app/models/player.rb
class Player < ApplicationRecord
    has_many :player_games
    has_many :games, through: :player_games
    has_secure_password
    validates :user_name, uniqueness: true, presence: true, length: { minimum: 3 }
    validates :password, length: { in: 6..20 }
end

app/models/player_games.rb
class PlayerGames < ApplicationRecord
    belongs_to :game
    belongs_to :player
end

app/models/quote.rb
class Quote < ApplicationRecord
    has_many :rounds
    has_many :games, through: :rounds
end

app/models/round.rb
class Round < ApplicationRecord
    belongs_to :game
    belongs_to :quote

    def wrong_answers
        incorrect_answers = []
        authors = []
        while incorrect_answers.length < 3
            sample = Quote.all.sample
            if sample.author != self.quote.author && !authors.include?(sample.author)
                incorrect_answers << sample
                authors << sample.author
            end
        end
        incorrect_answers
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        @current_user ||= Player.find(session[:player_id]) if session[:player_id]
    end

    def logged_in?
        !!current_user
    end

    def authorized?
        redirect_to '/login' unless logged_in?
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :current_user
   
    def create
        game = Game.create
        game.setup_game(session[:player_id])
        redirect_to "/games/#{game.id}/0"
    end

    def guess
        @player = current_user
        @game = Game.find(params[:id])
        @status = params[:status].to_i
        @answers = @game.rounds[@status].wrong_answers
        @answers << @game.rounds[@status].quote
        @answers.shuffle!
    end

    def assess
        @game = Game.find(params[:id])
        @status = params[:status].to_i
        @correct_answer = @game.rounds[@status].quote
        pg = PlayerGames.find_by(game_id: @game.id, player_id: session[:player_id])
        if params[:quote_id].to_i == @correct_answer.id
            @answer = "You're correct!"
           pg = PlayerGames.find_by(game_id: @game.id, player_id: session[:player_id])
           pg.update(score: pg.score + 10)
        else
            @answer = "You're bad at guessing!"
        end
        @score = pg.score
    end

    def complete
        @player = current_user
        @game = Game.find(params[:id])
        @status = params[:status].to_i
        pg = PlayerGames.find_by(game_id: @game.id, player_id: session[:player_id])
        @current_score = pg.score
        if @current_score > @game.game_highscore
            @game.update(game_highscore: @current_score)
            @game.game_highscore = @current_score
      
        end
        if @current_score > @player.player_highscore
            @player.player_highscore = @current_score
            @player.save(validate: false)
        end
  
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :current_user

    def index
        @players = Player.all
    end

    def show
        # byebug
        @player = Player.find(params[:id])
    end
    
    def new
        @player = Player.new
    end

    def create
        @player = Player.create(player_params)
        if @player.valid?
            @player.save
            session[:player_id] = @player.id
            redirect_to player_path(@player)
        else
            flash.now[:messages] = @player.errors.full_messages
            render :new
        end
    end

    def edit
        @player = Player.find(params[:id])
    end

    def update
        @player = Player.find(params[:id])
        if @player.update(player_params)
            redirect_to player_path(@player)
        else
            flash.now[:messages] = @player.errors.full_messages
            render :edit
        end
    end

    def destroy
        player = Player.find(params[:id])
        player.delete
        redirect_to '/'
    end

    private

    def player_params
        params.require(:player).permit(:user_name, :password, :motto, :player_highscore)
    end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :current_user
    def new
        @quote = Quote.new
    end

    def create
        @quote = Quote.create(quote_params)
        if @quote.valid?
            @quote.save
            redirect_to players_path
        else
            flash.now[:messages] = @quote.errors.full_messages
            render :new
        end
    end

    private

    def quote_params
        params.require(:quote).permit(:text, :author)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        player = Player.find_by(user_name: params[:user_name])
        if player && player.authenticate(params[:password])
            session[:player_id] = player.id
            redirect_to player_path(player)
        elsif player.nil?
            flash.now[:messages] = ["We could not find that username, please try again."]
            render :new
        else
            flash.now[:messages] = ["Username found, but the password you have tried is incorrect."]
            render :new
        end
    end

    def destroy
        session.delete(:player_id)
        redirect_to '/login'
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def welcome

    end

    def about 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/assess.html.erb
<h2><%= @answer %></h2><br><br>

<div style="text-align: center;">
    <h3>"<%= @correct_answer.text %>" was from <%= @correct_answer.author %></h3><br>
    <p>Your current score is:</p> <div style="font-size: 40px;"><p><%= @score %></p></div>
</div>


<div class="submit-holder">
    <% if @status >= 4 %>
        <%= button_to "How did I do?", "/games/#{@game.id}/complete", method: :get, class: "black ui button" %>
    <% else %>
       <%= button_to "Next Round ➜", "/games/#{@game.id}/#{@status + 1}", method: :get, class: "black ui button" %>
    <% end %>
</div>

app/views/games/complete.html.erb
<h2>Great Job Maybe! I don't really know how you feel about it!</h2><br><br>

<div style="text-align: center;">
    <h3>Your Results: <%= @current_score %> / 50</h3> 
    <h3>Your Highest Score Ever (like of all time): <%= @player.player_highscore %> </h3>
    <div class="submit-holder">
        <%= button_to "Start a New Game!", '/games', class: "black ui button" %>
    </div>
</div>

app/views/games/guess.html.erb
<div style="text-align: center"><h2 class="ui header"><%= "Round #{@status + 1}" %></h2></div><br>
<div class="ui card" style="margin: auto; width: 50%">
    <div class="ui two top attached basic buttons">
        <div class="ui button">
            <%= link_to @answers[0].author, "/games/#{@game.id}/#{@status}/#{@answers[0].id}", method: :post %>
        </div>
        <div class="ui button">
            <%= link_to @answers[1].author, "/games/#{@game.id}/#{@status}/#{@answers[1].id}", method: :post %>
        </div>
    </div>
    <div class="content" style="padding: 20px;">
        <div style="text-align: center">"<%= @game.quotes[@status].text %>"</div>
    </div>
    <div class="ui two bottom attached basic buttons">
        <div class="ui button">
            <%= link_to @answers[2].author, "/games/#{@game.id}/#{@status}/#{@answers[2].id}", method: :post %>
        </div>
        <div class="ui button">
            <%= link_to @answers[3].author, "/games/#{@game.id}/#{@status}/#{@answers[3].id}", method: :post %>
        </div>
    </div>
</div>
<!-- <%= @game.quotes[@status].text %><br>
<ol>
    <% @answers.each do |answer| %>
        <li><%= button_to answer.author, "/games/#{@game.id}/#{@status}/#{answer.id}" %></li>
    <% end %>
</ol> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🍿Fun Time 🍿</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path("favicon.ico") %>
  </head>

  <body>
  <div class="ui inverted menu" style="width: 100%; margin: auto" >
    <% if @current_user  %>
      <div class="header item">
          🍿Fun Time 🍿
        </div>
        <div class="header item">
          <%= link_to "New Game", '/games', method: :post %>  
        </div>
         <div class="header item">
          <%= link_to "All Players", '/players', method: :get %>  
        </div>
        <div class="header item">
          <%= link_to "Add Quote", '/quotes/new', method: :get %>  
        </div>
        <div class="right menu">
          <div class="header item">
            <%= link_to @current_user.user_name, "/players/#{@current_user.id}" %>
          </div>
          <div class="header item">
            <%= link_to "Logout", "/logout", method: :post %>
          </div>
          <div class="header item">
            <%= link_to "", "/logout", method: :post %>
          </div>
        </div>
    <% else %>
        <div class="right menu">
          <div class="header item">
            <%= link_to "Sign In", "/login" %>
          </div>
          <div class ="header item">
            <%= link_to "Sign Up", "/signup", method: :get %>
          </div>
        </div>
    <% end %>
  </div>
  <br>
  <div class="container" style="width: 65%; margin: auto">
  <br>
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/applicationcopy.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CharadesEmulator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<h2>Emerge a Player from their Cocoon</h2>

<div class="ui form error">
    <% if flash[:messages] %>
        <% flash[:messages].each do |message| %>
            <br><div class="ui error message"><%= message %></div>
        <% end %>
    <% end %>
</div>

<%= form_for @player, html: {class: "ui form" } do |f| %>
    <br>
    <div class="field">
        <%= f.text_field :user_name, options = { placeholder: "Username"} %>
    </div>
    <div class="field">
        <%= f.password_field :password, options = { placeholder: "Password"} %>
    </div>
        <div class="ui divider"></div>
    <div class="field">
        <%= f.text_area :motto, options = { placeholder: "Your Life Motto"} %>
    </div>
    <%= f.hidden_field :high_score, value: 0 %>
    <div class="submit-holder">
        <%= f.submit "Grow! Grow!", class:"black ui button"%>
<% end %>

app/views/players/index.html.erb
<h2>Look at all these PLAYERS!!!</h2> <br>
<div class="clowncontainers">
    <div class="ui cards">
        <% @players.each do |player| %>
            <div class="ui card"style="max-width: 18%; ">
                <% if player.player_highscore > 49 %>
                    <div class="image" ><img src="/../../assets/Screen Shot 2019-09-13 at 10.11.37 AM.png"></div>
                <% else %>
                    <div class="image" ><img src="/../../assets/Screen Shot 2019-09-13 at 10.05.53 AM.png"></div>
                <% end %>
                <div class="content" style="height: ">
                    <div class="header"><%= link_to player.user_name, "/players/#{player.id}" %></div>
                    <div class= "meta">Last Played <%= player.updated_at.month %>/<%= player.updated_at.day %></div>
                </div>
                
            </div>
        <% end %>
    </div>
</div>

app/views/players/new.html.erb
<h2>Grow a Player from Scratch</h2>
<div class="ui form error">
    <% if flash[:messages] %>
        <% flash[:messages].each do |message| %>
            <div class="ui error message"><%= message %></div>
        <% end %>
    <% end %>
</div>

<%= form_for @player, html: {class: "ui form" } do |f| %>
    <br>
    <div class="field">
        <%= f.text_field :user_name, options = { placeholder: "Username"} %>
    </div>
    <div class="field">
        <%= f.password_field :password, options = { placeholder: "Password"} %>
    </div>
        <div class="ui divider"></div>
    <div class="field">
        <%= f.text_area :motto, options = { placeholder: "Your Life Motto"} %>
    </div>
    <%= f.hidden_field :high_score, value: 0 %>
    <div class="submit-holder">
        <%= f.submit "Grow! Grow!", class:"black ui button"%>
<% end %>

app/views/players/show.html.erb
<div class="ui segments" >
    <div class="ui segment">
        <h2><%= @player.user_name %></h2>
    </div>
    <div class="ui horizontal segments">
        <div class="ui segment">
            Highscore: <%= @player.player_highscore %> 
        </div>
        <div class="ui segment">
            <%= link_to "Start a New Game!", '/games', method: :post %> 
        </div>
    </div>
    <div class="ui horizontal segments">
        <div class="ui segment">
            Motto: <%= @player.motto %>
        </div>
        <div class="ui segment">
            <%= link_to "Edit Player", edit_player_path %> 
        </div>
    </div>
    <div class="ui segment">
        <%= link_to "Wipe yourself off the face of this program. However, just know, that - if you do this, there's no coming back from it.", "/players/#{@player.id}" %> <br><br>
    </div>
</div>

app/views/quotes/new.erb
<h2>Add Quote</h2>
<div class="ui form error">
    <% if flash[:messages] %>
        <% flash[:messages].each do |message| %>
            <div class="ui error message"><%= message %></div>
        <% end %>
    <% end %>
</div>

<%= form_for @quote, html: {class: "ui form" } do |f| %>
    <br>
      <div class="field">
        <%= f.text_area :text, options = { placeholder: "Type Quote Here"} %>
        </div>
    <div class="ui divider"></div>
      <div class="field">
        <%= f.text_field :author, options = { placeholder: "Movie Title"} %>
    </div>
    <%= f.hidden_field :high_score, value: 0 %>
    <div class="submit-holder">
        <%= f.submit "Add Quote!", class:"black ui button"%>
<% end %>